version: "2"
linters:
#  default: all
  disable-all : true
  enable:
    - gocritic
#    - revive
    - govet
    - ineffassign
    - misspell
    - staticcheck

  disable:
    # Disable temporarily while developing
    - unused
    - exhaustruct
    - wsl
    - varnamelen
    - err113
    - depguard  # Temporarily disabled while fixing configuration

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 2
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
  go: "1.24"
  concurrency: 4

linters-settings:
  depguard:
    rules:
      Main:  # Note: Using "Main" with capital M as that's what the error message refers to
        list-type: allowlist
        include-go-root: true
        packages:
          - github.com/labstack/echo/v4
          - github.com/one-project-one-month/Hotel-Booking-Management-System-Go
          - github.com/spf13/viper
          - gorm.io/gorm
          - gorm.io/driver/postgres
          - github.com/google/uuid
          - golang.org/x/...
          - github.com/...
  
  exhaustruct:
    exclude:
      - 'gorm.Config'

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - 'packageComment'
          - 'fieldsComment'
          - 'functionComment'

  varnamelen:
    ignore-names:
      - err
      - db
      - tx
      - v
