version: "2"
linters:
  default: all
  enable:
    - gocritic
    - revive
    - govet
    - ineffassign
    - misspell
    - staticcheck

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 2
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
  go: "1.24"
  concurrency: 4
