version: "3.9"

services:
  hbms:
    build:
      context: .
    container_name: hbms_app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hbms_net
    ports:
      - "8080:8080"


  db:
    image: postgres:15
    container_name: hbms_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: hotel_booking
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql  # 👈 auto-executes on container start
    networks:
      - hbms_net
    ports:
      - "5432:5432"

networks:
  hbms_net:
    driver: bridge
