### Local Environment
@baseUrl = http://localhost:8080/api/v1/room

### Get All Room
GET {{baseUrl}}

### Get Room By ID
GET {{baseUrl}}/06acbee1-b0bf-4dfd-96a3-732ee4778548

### Create Room
POST {{baseUrl}}
Content-Type: application/json

{
  "guestLimit": 12,
  "imgURL": ["https://www.novotellondonwest.co.uk/images/slider_superiorRooms2.jpg"],
  "price": 12.12,
  "roomNo": 101,
  "status": "Available",
  "type": "Deluxe"
}

### Update Room
PATCH {{baseUrl}}/016910ed-971e-4c22-ac54-b396a018cd04
Content-Type: application/json

{
  "guestLimit": 12,
  "imgURL": ["https://www.novotellondonwest.co.uk/images/slider_superiorRooms2.jpg"],
  "price": 122,
  "roomNo": 101,
  "status": "CheckedIn",
  "type": "Deluxe"
}

### Delete Room By ID
DELETE {{baseUrl}}/06acbee1-b0bf-4dfd-96a3-732ee4778548

### Update Room Status
PATCH {{baseUrl}}/016910ed-971e-4c22-ac54-b396a018cd04/status
Content-Type: application/json

{
  "status": "Booked"
}

### Update Room IsFeatured
PATCH {{baseUrl}}/016910ed-971e-4c22-ac54-b396a018cd04/is_featured
Content-Type: application/json

### Search Room By Guest Limit
GET {{baseUrl}}/search?total_guests=3