package events

const (
	COUPONFETCHED      = "COUPON_FETCHED"
	BOOKINGFETCHED     = "BOOKING_FETCHED"
	BANKACCOUNTFETCHED = "BANK_ACCOUNT_FETCHED"
	USERFINDBYID       = "USER_FIND_ID"
	USERFINDBYEMAIL    = "USER_FIND_EMAIL"
	USERCREATED        = "USER_CREATED"
	JWTCONFIG          = "JWT_CONFIG"
)
