package events

const (
	COUPONFETCHED         = "COUPON_FETCHED"
	BOOKINGFETCHED        = "BOOKING_FETCHED"
	BANKACCOUNTFETCHED    = "BANK_ACCOUNT_FETCHED"
	USERFINDBYID          = "USER_FIND_ID"
	USERFINDBYEMAIL       = "USER_FIND_EMAIL"
	USERCREATED           = "USER_CREATED"
	USERFINDBYPHONENUMBER = "USER_FIND_PHONE_NUMBER"
	JWTCONFIG             = "JWT_CONFIG"
	BOOKINGUPDATED        = "BOOKING_UPDATED"
	CHECKINOUTCREATED     = "CHECKINOUT_CREATED"
	ROOMFINDBYID          = "ROOM_FIND_ID"
	ROOMCREATED           = "ROOM_CREATED"
)
